import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ICONS } from '../constants';
import { storageService } from '../services/storageService';
import { Crianca, Responsavel } from '../types';
import PaisBackground from '../components/PaisBackground';

const formatPhone = (value: string) => {
  if (!value) return value;
  const phoneNumber = value.replace(/[^\d]/g, '');
  const phoneNumberLength = phoneNumber.length;
  if (phoneNumberLength < 3) return phoneNumber;
  if (phoneNumberLength < 7) {
    return `(${phoneNumber.slice(0, 2)}) ${phoneNumber.slice(2)}`;
  }
  return `(${phoneNumber.slice(0, 2)}) ${phoneNumber.slice(2, 7)}-${phoneNumber.slice(7, 11)}`;
};

const CriancaCadastro: React.FC = () => {
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({
    nome: '', sobrenome: '', dataNascimento: '', observacoes: ''
  });
  const [responsaveis, setResponsaveis] = useState<Responsavel[]>([
    { nome: '', whatsapp: '', parentesco: 'Pai' }
  ]);

  const handleResponsavelChange = (index: number, field: keyof Responsavel, value: string) => {
    const newResponsaveis = [...responsaveis];
    if (field === 'whatsapp') {
      newResponsaveis[index][field] = formatPhone(value);
    } else {
      newResponsaveis[index][field] = value;
    }
    setResponsaveis(newResponsaveis);
  };

  const addResponsavel = () => {
    if (responsaveis.length < 3) {
      setResponsaveis([...responsaveis, { nome: '', whatsapp: '', parentesco: 'Mãe' }]);
    }
  };

  const removeResponsavel = (index: number) => {
    if (responsaveis.length > 1) {
      const newResponsaveis = [...responsaveis];
      newResponsaveis.splice(index, 1);
      setResponsaveis(newResponsaveis);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const newKid: Omit<Crianca, 'id'> = {
        ...form,
        responsavelNome: '', // will be generated by storageService
        whatsapp: '', // will be generated by storageService
        responsaveis: responsaveis,
        createdAt: new Date().toISOString()
      };
      await storageService.addCrianca(newKid);
      setDone(true);
    } catch (error) {
      alert("Erro ao salvar cadastro. Verifique os dados.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (done) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6 relative overflow-hidden">
        <PaisBackground />
        <div className="bg-white w-full max-w-md rounded-[2.5rem] p-10 shadow-2xl text-center animate-in zoom-in duration-500 relative z-10">
          <div className="bg-green-100 text-green-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl">
            {ICONS.CheckCircle}
          </div>
          <h2 className="text-2xl font-black text-purple-dark mb-3 uppercase">Sucesso!</h2>
          <p className="text-gray-text font-bold mb-8 text-sm">Agora você já pode realizar o Pré-Check-in.</p>
          <button 
            onClick={() => {
              // Ensure zoom reset by reloading if necessary or just navigating
              navigate('/pais');
            }}
            className="w-full bg-yellow-main text-purple-dark font-black py-4 rounded-2xl shadow-xl text-xs uppercase hover:bg-yellow-400 transition-colors border-b-4 border-yellow-600"
          >
            VOLTAR AO INÍCIO
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 flex flex-col items-center relative overflow-hidden">
      <PaisBackground />
      <div className="w-full max-w-2xl relative z-10">
        <button 
          onClick={() => navigate('/pais')}
          className="mb-6 mt-2 flex items-center gap-2 text-white font-black uppercase text-[10px] tracking-widest hover:text-yellow-main transition-colors"
        >
          {ICONS.ArrowLeft} Voltar
        </button>

        <div className="bg-white rounded-[2.5rem] p-7 md:p-10 shadow-2xl border-b-6 border-yellow-main">
          <h1 className="text-2xl font-black text-purple-dark mb-1 uppercase tracking-tight">Cadastro</h1>
          <p className="text-gray-text font-bold mb-8 text-xs uppercase opacity-60">Primeiro acesso do seu filho.</p>

          <form onSubmit={handleSave} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Nome</label>
                <input required type="text" value={form.nome} onChange={e => setForm({...form, nome: e.target.value})} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm" placeholder="Ex: Lucas" />
              </div>
              <div>
                <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Sobrenome</label>
                <input required type="text" value={form.sobrenome} onChange={e => setForm({...form, sobrenome: e.target.value})} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm" placeholder="Ex: Silva" />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Nascimento</label>
                <input 
                  required 
                  type="date" 
                  value={form.dataNascimento} 
                  onChange={e => setForm({...form, dataNascimento: e.target.value})} 
                  className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm appearance-none" 
                  style={{ minHeight: '3rem' }}
                />
              </div>
            </div>

            <div className="mt-6 mb-4">
              <h3 className="text-sm font-black text-purple-dark uppercase tracking-widest border-b-2 border-gray-100 pb-2 mb-4">Responsáveis</h3>
              
              {responsaveis.map((resp, index) => (
                <div key={index} className="bg-gray-50 p-4 rounded-2xl mb-4 border border-gray-200 relative">
                  {index > 0 && (
                    <button 
                      type="button" 
                      onClick={() => removeResponsavel(index)}
                      className="absolute top-3 right-3 text-red-500 hover:text-red-700 p-1"
                    >
                      {ICONS.Trash}
                    </button>
                  )}
                  <h4 className="text-[10px] font-black text-purple-main uppercase tracking-widest mb-3">Responsável {index + 1} {index === 0 && '(Principal)'}</h4>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-3">
                    <div>
                      <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Nome</label>
                      <input required type="text" value={resp.nome} onChange={e => handleResponsavelChange(index, 'nome', e.target.value)} className="w-full bg-white p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm shadow-sm" placeholder="Ex: João" />
                    </div>
                    <div>
                      <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Parentesco</label>
                      <select required value={resp.parentesco} onChange={e => handleResponsavelChange(index, 'parentesco', e.target.value)} className="w-full bg-white p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm shadow-sm appearance-none">
                        <option value="Pai">Pai</option>
                        <option value="Mãe">Mãe</option>
                        <option value="Avô/Avó">Avô/Avó</option>
                        <option value="Tio/Tia">Tio/Tia</option>
                        <option value="Outro">Outro</option>
                      </select>
                    </div>
                  </div>
                  <div>
                    <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">WhatsApp</label>
                    <input required type="tel" value={resp.whatsapp} onChange={e => handleResponsavelChange(index, 'whatsapp', e.target.value)} className="w-full bg-white p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none text-sm shadow-sm" placeholder="(67) 99999-9999" />
                  </div>
                </div>
              ))}

              {responsaveis.length < 3 && (
                <button 
                  type="button" 
                  onClick={addResponsavel}
                  className="w-full border-2 border-dashed border-yellow-main text-yellow-600 font-black py-3 rounded-2xl hover:bg-yellow-50 transition-all text-xs uppercase tracking-widest flex items-center justify-center gap-2"
                >
                  {ICONS.Plus} Adicionar outro responsável
                </button>
              )}
            </div>

            <div>
              <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Obs. Médicas</label>
              <textarea rows={2} value={form.observacoes} onChange={e => setForm({...form, observacoes: e.target.value})} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main outline-none resize-none text-sm" placeholder="Alergias ou restrições..." />
            </div>

            <button 
              type="submit" 
              disabled={isSubmitting}
              className="w-full bg-yellow-main text-purple-dark font-black py-5 rounded-2xl shadow-xl hover:bg-yellow-400 transition-all disabled:opacity-50 text-xs uppercase tracking-widest border-b-4 border-yellow-600"
            >
              {isSubmitting ? 'SALVANDO...' : 'FINALIZAR CADASTRO'}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default CriancaCadastro;