import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ICONS } from '../constants';
import { formatPhone } from '../utils';
import { storageService } from '../services/storageService';
import { Crianca } from '../types';
import PaisBackground from '../components/PaisBackground';
import { globalProgress } from '../components/GlobalProgress';

const CriancaCadastro: React.FC = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState<1 | 2>(1);
  const [sexo, setSexo] = useState<'F' | 'M'>('F');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [done, setDone] = useState(false);
  const [form, setForm] = useState({
    nome: '', sobrenome: '', dataNascimento: '', observacoes: ''
  });
  const [responsaveis, setResponsaveis] = useState<{ nome: string; whatsapp: string; parentesco: string }[]>([
    { nome: '', whatsapp: '', parentesco: 'Pai' }
  ]);
  const [neurodivergente, setNeurodivergente] = useState<boolean | null>(null);
  const [neurodivergenteOpcoes, setNeurodivergenteOpcoes] = useState<string[]>([]);
  const [neurodivergenteOutro, setNeurodivergenteOutro] = useState('');

  const handleNeuroChange = (isNeuro: boolean) => {
    setNeurodivergente(isNeuro);
    if (!isNeuro) {
      setNeurodivergenteOpcoes([]);
      setNeurodivergenteOutro('');
    }
  };

  const toggleNeuroOpcao = (opcao: string) => {
    setNeurodivergenteOpcoes(prev => {
      const isSelected = prev.includes(opcao);
      const newOptions = isSelected ? prev.filter(o => o !== opcao) : [...prev, opcao];
      if (isSelected && opcao === 'Outro') {
        setNeurodivergenteOutro('');
      }
      return newOptions;
    });
  };

  const handleResponsavelChange = (index: number, field: 'nome' | 'whatsapp' | 'parentesco', value: string) => {
    const newResponsaveis = [...responsaveis];
    if (field === 'whatsapp') {
      newResponsaveis[index][field] = formatPhone(value);
    } else {
      newResponsaveis[index][field] = value;
    }
    setResponsaveis(newResponsaveis);
  };

  const addResponsavel = () => {
    if (responsaveis.length < 3) {
      setResponsaveis([...responsaveis, { nome: '', whatsapp: '', parentesco: 'Mãe' }]);
    }
  };

  const removeResponsavel = (index: number) => {
    if (responsaveis.length > 1) {
      const newResponsaveis = [...responsaveis];
      newResponsaveis.splice(index, 1);
      setResponsaveis(newResponsaveis);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    if (responsaveis.length === 0) {
      alert("Por favor, adicione pelo menos um responsável.");
      return;
    }
    for (const resp of responsaveis) {
      if (!resp.nome.trim()) {
        alert("O nome do responsável é obrigatório.");
        return;
      }
      const digits = resp.whatsapp.replace(/\D/g, "");
      if (digits.length < 10) {
        alert("O telefone do responsável está incompleto ou vazio.");
        return;
      }
    }

    if (neurodivergente === true) {
      if (neurodivergenteOpcoes.length === 0) {
        alert("Por favor, selecione pelo menos uma opção de neurodivergência.");
        return;
      }
      if (neurodivergenteOpcoes.includes('Outro') && !neurodivergenteOutro.trim()) {
        alert("Por favor, informe qual a neurodivergência no campo 'Outro'.");
        return;
      }
    }

    setIsSubmitting(true);
    globalProgress.start('Salvando...');

    try {
      const finalNeuroOpcoes = neurodivergente ? neurodivergenteOpcoes : [];
      const finalNeuroOutro = neurodivergente && neurodivergenteOpcoes.includes('Outro') ? neurodivergenteOutro.trim() : '';

      const newKid: Omit<Crianca, 'id'> = {
        ...form,
        sexo,
        responsavelNome: '', // will be generated by storageService
        whatsapp: '', // will be generated by storageService
        responsaveis: responsaveis,
        neurodivergente: neurodivergente === true,
        neurodivergenteOpcoes: finalNeuroOpcoes,
        neurodivergenteOutro: finalNeuroOutro,
        createdAt: new Date().toISOString()
      };
      await storageService.addCrianca(newKid);
      setDone(true);
    } catch (error) {
      alert("Erro ao salvar cadastro. Verifique os dados.");
    } finally {
      setIsSubmitting(false);
      globalProgress.stop();
    }
  };

  if (done) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6 relative overflow-hidden">
        <PaisBackground />
        <div className="bg-white w-full max-w-md rounded-[2.5rem] p-10 shadow-2xl text-center animate-in zoom-in duration-500 relative z-10 border-b-8 border-yellow-main">
          <div className="bg-green-100 text-green-600 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 text-4xl shadow-inner border-4 border-green-200">
            {ICONS.CheckCircle}
          </div>
          <h2 className="kids-font text-4xl font-black text-purple-dark mb-3 uppercase tracking-tight">Eba! Sucesso!</h2>
          <p className="text-gray-text font-bold mb-8 text-sm uppercase opacity-70">Criança cadastrada com alegria!</p>
          <button 
            onClick={() => {
              navigate('/pais');
            }}
            className="w-full bg-yellow-main text-purple-dark font-black py-5 rounded-[2rem] shadow-xl text-sm uppercase tracking-widest hover:bg-yellow-400 transition-all border-b-8 border-yellow-600 active:border-b-0 active:translate-y-2 flex items-center justify-center gap-2"
          >
            VOLTAR AO INÍCIO
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 flex flex-col items-center relative overflow-hidden">
      <PaisBackground />
      <div className="w-full max-w-2xl relative z-10">
        <button 
          onClick={() => step === 2 ? setStep(1) : navigate('/pais')}
          className="mb-6 mt-2 flex items-center gap-2 text-white font-black uppercase text-[10px] tracking-widest hover:text-yellow-main transition-colors"
        >
          {ICONS.ArrowLeft} Voltar
        </button>

        <div className="bg-white rounded-[2.5rem] p-5 md:p-10 shadow-2xl border-b-8 border-yellow-main">
          {step === 1 ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 flex flex-col items-center text-center">
              <h1 className="kids-font text-3xl font-black text-purple-dark mb-2 uppercase tracking-tight">Quem é a criança?</h1>
              <p className="text-gray-text font-bold mb-8 text-sm uppercase opacity-60">Selecione para personalizar</p>
              
              {/* DESKTOP VERSION */}
              <div className="hidden md:flex flex-col items-center w-full">
                <div className={`w-48 h-48 mb-8 rounded-full bg-white shadow-xl overflow-hidden border-8 transition-all duration-500 ${sexo === 'F' ? 'border-pink-400 ring-4 ring-pink-200 ring-offset-4' : 'border-blue-400 ring-4 ring-blue-200 ring-offset-4'}`}>
                  <img 
                    src={sexo === 'F' ? "/avatar-menina.svg" : "/avatar-menino.svg"} 
                    alt={sexo === 'F' ? "Menina" : "Menino"} 
                    className="w-full h-full object-cover transition-transform duration-500 hover:scale-110"
                  />
                </div>

                <div className="flex bg-gray-50 p-2 rounded-[2rem] mb-10 w-full max-w-sm shadow-inner border-2 border-gray-100">
                  <button
                    type="button"
                    onClick={() => setSexo('F')}
                    className={`flex-1 py-4 px-4 rounded-[1.5rem] font-black text-sm uppercase tracking-widest transition-all duration-300 ${
                      sexo === 'F' 
                        ? 'bg-pink-400 text-white shadow-md transform scale-105' 
                        : 'text-gray-400 hover:text-pink-400 hover:bg-pink-50'
                    }`}
                  >
                    Menina
                  </button>
                  <button
                    type="button"
                    onClick={() => setSexo('M')}
                    className={`flex-1 py-4 px-4 rounded-[1.5rem] font-black text-sm uppercase tracking-widest transition-all duration-300 ${
                      sexo === 'M' 
                        ? 'bg-blue-400 text-white shadow-md transform scale-105' 
                        : 'text-gray-400 hover:text-blue-400 hover:bg-blue-50'
                    }`}
                  >
                    Menino
                  </button>
                </div>
              </div>

              {/* MOBILE VERSION */}
              <div className="flex md:hidden flex-col gap-4 w-full max-w-sm mb-10">
                <button
                  type="button"
                  onClick={() => setSexo('F')}
                  className={`flex items-center p-3 rounded-[2rem] border-4 transition-all duration-300 shadow-sm w-full ${
                    sexo === 'F' 
                      ? 'border-pink-400 bg-pink-50 ring-2 ring-pink-200 ring-offset-2' 
                      : 'border-gray-100 bg-white hover:border-pink-200'
                  }`}
                >
                  <div className={`w-16 h-16 rounded-full overflow-hidden border-2 flex-shrink-0 ${sexo === 'F' ? 'border-pink-400' : 'border-gray-200'}`}>
                    <img src="/avatar-menina.svg" alt="Menina" className="w-full h-full object-cover" />
                  </div>
                  <span className={`ml-4 font-black text-lg uppercase tracking-widest ${sexo === 'F' ? 'text-pink-500' : 'text-gray-400'}`}>Menina</span>
                </button>

                <button
                  type="button"
                  onClick={() => setSexo('M')}
                  className={`flex items-center p-3 rounded-[2rem] border-4 transition-all duration-300 shadow-sm w-full ${
                    sexo === 'M' 
                      ? 'border-blue-400 bg-blue-50 ring-2 ring-blue-200 ring-offset-2' 
                      : 'border-gray-100 bg-white hover:border-blue-200'
                  }`}
                >
                  <div className={`w-16 h-16 rounded-full overflow-hidden border-2 flex-shrink-0 ${sexo === 'M' ? 'border-blue-400' : 'border-gray-200'}`}>
                    <img src="/avatar-menino.svg" alt="Menino" className="w-full h-full object-cover" />
                  </div>
                  <span className={`ml-4 font-black text-lg uppercase tracking-widest ${sexo === 'M' ? 'text-blue-500' : 'text-gray-400'}`}>Menino</span>
                </button>
              </div>

              <button 
                onClick={() => setStep(2)}
                className="w-full bg-yellow-main text-purple-dark font-black py-5 rounded-[2rem] shadow-xl hover:bg-yellow-400 transition-all transform active:scale-95 text-sm uppercase tracking-widest border-b-8 border-yellow-600 flex items-center justify-center gap-3"
              >
                PROSSEGUIR {ICONS.ChevronRight}
              </button>
            </div>
          ) : (
            <div className="animate-in fade-in slide-in-from-right-8 duration-500">
              <div className="flex items-center gap-5 mb-8 bg-purple-main/5 p-4 rounded-[2rem] border-2 border-purple-main/10">
                <div className={`w-16 h-16 rounded-full overflow-hidden border-4 shadow-md flex-shrink-0 ${sexo === 'F' ? 'border-pink-300 bg-pink-100' : 'border-blue-300 bg-blue-100'}`}>
                  <img 
                    src={sexo === 'F' ? '/avatar-menina.svg' : '/avatar-menino.svg'}
                    alt="Avatar" 
                    className="w-full h-full object-cover"
                  />
                </div>
                <div>
                  <h1 className="kids-font text-2xl font-black text-purple-dark leading-none mb-1">Dados do(a) {sexo === 'F' ? 'Menina' : 'Menino'}</h1>
                  <p className="text-gray-text font-bold text-[10px] uppercase tracking-widest opacity-60">Vamos lá, é rapidinho!</p>
                </div>
              </div>

              <form onSubmit={handleSave} className="space-y-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2 px-1">Nome</label>
                    <input required type="text" value={form.nome} onChange={e => setForm({...form, nome: e.target.value})} className="w-full bg-gray-light p-4 rounded-2xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm shadow-inner" placeholder="Ex: Lucas" />
                  </div>
                  <div>
                    <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2 px-1">Sobrenome</label>
                    <input required type="text" value={form.sobrenome} onChange={e => setForm({...form, sobrenome: e.target.value})} className="w-full bg-gray-light p-4 rounded-2xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm shadow-inner" placeholder="Ex: Silva" />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  <div>
                    <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2 px-1">Nascimento</label>
                    <input 
                      required 
                      type="date" 
                      value={form.dataNascimento} 
                      onChange={e => setForm({...form, dataNascimento: e.target.value})} 
                      className="w-full bg-gray-light p-4 rounded-2xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm appearance-none shadow-inner" 
                      style={{ minHeight: '3.5rem' }}
                    />
                  </div>
                </div>

                <div className="bg-gray-50 p-5 rounded-[2rem] border-2 border-gray-100 mt-5">
                  <label className="block text-[10px] font-black text-purple-main uppercase tracking-widest mb-3 px-1">A criança é neurodivergente?</label>
                  <div className="flex gap-4">
                    <button
                      type="button"
                      onClick={() => handleNeuroChange(true)}
                      className={`flex-1 py-3 px-4 rounded-xl font-black text-sm uppercase tracking-widest transition-all ${neurodivergente === true ? 'bg-purple-main text-white shadow-md' : 'bg-white border-2 border-gray-200 text-gray-400 hover:border-purple-300'}`}
                    >
                      SIM
                    </button>
                    <button
                      type="button"
                      onClick={() => handleNeuroChange(false)}
                      className={`flex-1 py-3 px-4 rounded-xl font-black text-sm uppercase tracking-widest transition-all ${neurodivergente === false ? 'bg-purple-main text-white shadow-md' : 'bg-white border-2 border-gray-200 text-gray-400 hover:border-purple-300'}`}
                    >
                      NÃO
                    </button>
                  </div>

                  {neurodivergente === true && (
                    <div className="mt-4 animate-in fade-in slide-in-from-top-2">
                      <div className="grid grid-cols-2 md:flex md:flex-wrap gap-3 mb-4">
                        {['TEA', 'TDAH'].map(opcao => (
                          <label key={opcao} className="flex items-center gap-2 cursor-pointer bg-white px-4 py-2 rounded-xl border-2 border-gray-100 hover:border-purple-200 transition-colors justify-center md:justify-start">
                            <input 
                              type="checkbox" 
                              checked={neurodivergenteOpcoes.includes(opcao)}
                              onChange={() => toggleNeuroOpcao(opcao)}
                              className="w-4 h-4 accent-purple-main"
                            />
                            <span className="font-bold text-sm text-gray-600">{opcao}</span>
                          </label>
                        ))}
                        <label className="col-span-2 flex items-center gap-2 cursor-pointer bg-white px-4 py-2 rounded-xl border-2 border-gray-100 hover:border-purple-200 transition-colors justify-center md:justify-start md:w-auto w-full">
                          <input 
                            type="checkbox" 
                            checked={neurodivergenteOpcoes.includes('Outro')}
                            onChange={() => toggleNeuroOpcao('Outro')}
                            className="w-4 h-4 accent-purple-main"
                          />
                          <span className="font-bold text-sm text-gray-600">Outro</span>
                        </label>
                      </div>
                      
                      {neurodivergenteOpcoes.includes('Outro') && (
                        <div className="animate-in fade-in zoom-in duration-200">
                          <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2 px-1">Informe qual:</label>
                          <input 
                            required 
                            type="text" 
                            value={neurodivergenteOutro} 
                            onChange={e => setNeurodivergenteOutro(e.target.value)} 
                            className="w-full bg-white p-4 rounded-2xl font-bold border-2 border-gray-200 focus:border-purple-main transition-colors outline-none text-sm shadow-sm" 
                            placeholder="Digite aqui..." 
                          />
                        </div>
                      )}
                    </div>
                  )}
                </div>

                <div className="mt-8 mb-6">
                  <h3 className="kids-font text-xl font-black text-purple-dark mb-4 flex items-center gap-3">
                    <span className="bg-yellow-main text-purple-dark w-8 h-8 rounded-full flex items-center justify-center text-sm shadow-sm">{ICONS.Users}</span>
                    Responsáveis
                  </h3>
                  
                  {responsaveis.map((resp, index) => (
                    <div key={index} className="bg-white p-4 md:p-5 rounded-[2rem] mb-4 border-2 border-gray-100 shadow-sm relative group hover:border-purple-main/30 transition-colors">
                      {index > 0 && (
                        <button 
                          type="button" 
                          onClick={() => removeResponsavel(index)}
                          className="absolute top-4 right-4 text-red-400 hover:text-red-600 p-2 bg-red-50 rounded-xl transition-colors"
                        >
                          {ICONS.Trash}
                        </button>
                      )}
                      <h4 className="text-[10px] font-black text-purple-main uppercase tracking-widest mb-4 flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-purple-main"></div>
                        Responsável {index + 1} {index === 0 && '(Principal)'}
                      </h4>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div>
                          <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Nome</label>
                          <input required type="text" value={resp.nome} onChange={e => handleResponsavelChange(index, 'nome', e.target.value)} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm shadow-inner" placeholder="Ex: João" />
                        </div>
                        <div>
                          <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">Parentesco</label>
                          <select required value={resp.parentesco} onChange={e => handleResponsavelChange(index, 'parentesco', e.target.value)} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm shadow-inner appearance-none">
                            <option value="Pai">Pai</option>
                            <option value="Mãe">Mãe</option>
                            <option value="Avô/Avó">Avô/Avó</option>
                            <option value="Tio/Tia">Tio/Tia</option>
                            <option value="Outro">Outro</option>
                          </select>
                        </div>
                      </div>
                      <div>
                        <label className="block text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1.5 px-1">WhatsApp</label>
                        <input required type="tel" value={resp.whatsapp} onChange={e => handleResponsavelChange(index, 'whatsapp', e.target.value)} className="w-full bg-gray-light p-3.5 rounded-xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none text-sm shadow-inner" placeholder="(67) 99999-9999" />
                      </div>
                    </div>
                  ))}

                  {responsaveis.length < 3 && (
                    <button 
                      type="button" 
                      onClick={addResponsavel}
                      className="w-full border-2 border-dashed border-yellow-main text-yellow-600 font-black py-4 rounded-[2rem] hover:bg-yellow-50 transition-all text-xs uppercase tracking-widest flex items-center justify-center gap-2"
                    >
                      {ICONS.Plus} Adicionar outro responsável
                    </button>
                  )}
                </div>

                <div>
                  <label className="block text-[10px] font-black text-gray-500 uppercase tracking-widest mb-2 px-1">Obs. Médicas</label>
                  <textarea rows={2} value={form.observacoes} onChange={e => setForm({...form, observacoes: e.target.value})} className="w-full bg-gray-light p-4 rounded-2xl font-bold border-2 border-transparent focus:border-purple-main focus:bg-white transition-colors outline-none resize-none text-sm shadow-inner" placeholder="Alergias ou restrições..." />
                </div>

                <button 
                  type="submit" 
                  disabled={isSubmitting}
                  className="w-full bg-yellow-main text-purple-dark font-black py-5 rounded-[2rem] shadow-xl hover:bg-yellow-400 transition-all transform active:scale-95 disabled:opacity-50 text-sm uppercase tracking-widest border-b-8 border-yellow-600 flex items-center justify-center gap-3 mt-8"
                >
                  {isSubmitting ? 'SALVANDO...' : 'FINALIZAR CADASTRO'}
                </button>
              </form>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CriancaCadastro;